# Кэш сборки
org.gradle.caching=true

# Кэш конфигурации (пропускает фазу настройки при повторных сборках)
org.gradle.configuration-cache=true

# Параллельная сборка модулей
org.gradle.parallel=true

# Память для JVM (чтобы не тормозило на слабых машинах)
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError

# Демон Gradle (ускоряет повторные сборки)
org.gradle.daemon=true
